#!/bin/bash

personalities=$(python3 -c "import nikkyai; n = nikkyai.NikkyAI()
for p in sorted(n.get_personalities()):
    print(p)")

parallel "./get_corpus.py {} $* | ./train.py {} $*" ::: $personalities
